# Generated by Django 3.1.6 on 2021-02-15 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exehubapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
