# Generated by Django 3.1.6 on 2021-02-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exehubapp', '0004_event_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_server_admin', models.BooleanField()),
                ('dob', models.DateField()),
                ('email', models.CharField(max_length=45)),
                ('irc_user', models.CharField(max_length=45)),
                ('hashed_password', models.BinaryField(verbose_name=64)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='set_date_time',
            field=models.DateTimeField(),
        ),
    ]
