# Generated by Django 3.1.6 on 2021-02-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exehubapp', '0006_auto_20210215_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=600),
        ),
    ]
