# Generated by Django 3.1.6 on 2021-02-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exehubapp', '0008_attendee_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'attendees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('event_owner', models.CharField(blank=True, max_length=747, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('attendees_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('attendees_max', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_group_admin', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UniGroups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50, unique=True)),
                ('group_owner', models.CharField(blank=True, max_length=747, null=True)),
                ('group_email', models.CharField(max_length=254, unique=True)),
                ('group_irc', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'uni_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_server_admin', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('email', models.CharField(max_length=254, unique=True)),
                ('irc_username', models.CharField(blank=True, max_length=9, null=True)),
                ('password_hash', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=747)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='group',
        ),
        migrations.RemoveField(
            model_name='member',
            name='group',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attendee',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
